//
//  Class5Questions.swift
//  Spellquiz
//
//  Created by Jagdeep on 02/07/18.
//  Copyright © 2018 biroke. All rights reserved.
//

import Foundation

class questionBank {
    var list = [Question]()
    init() {
        list.append(Question(imgae: "", question: "When driving to an unfamiliar area, you:", option_A: "A. Can depend on road signs to help you find your way", option_B: "B. Should use a map and plan your trip", option_C: "C. Only have to know generally where your destination is", option_D: "D. Should always choose the most direct route", rightAnswer: 2))
        list.append(Question(imgae: "", question: "A. Which of the following influences your driving actions most?", option_A: "A. Your experience", option_B: "B. Your age", option_C: "C. Your attitude towards driving", option_D: "D. Your reaction time", rightAnswer: 3))
       
         list.append(Question(imgae: "", question: " Alcoholic beverages will affect you:", option_A: "A. more rapidly just after eating", option_B: "B. more rapidly on an empty stomach", option_C: "C. the same way at all times", option_D: "D. only if you have more than two drinks", rightAnswer: 2))
         list.append(Question(imgae: "", question: "      An aggressive driver:", option_A: "A.      is purposely in a hurry, competing with other traffic", option_B: "B. shows little or no respect for traffic laws", option_C: "C.      is someone to avoid, when you're driving ", option_D: "D. all of the above", rightAnswer: 4))
         list.append(Question(imgae: "", question: "      In Manitoba, to act as a supervising driver for a new Class 5 driver, a driver must be fully licenced in Class 5 for what period of time?  ", option_A: "A. 5 years", option_B: "B. 3 years", option_C: "C. 2 years", option_D: "D. 1 years", rightAnswer: 2))
         list.append(Question(imgae: "", question: "     The most important thing in any driving situation is the:", option_A: "A. driver", option_B: "B. Vehicle", option_C: "C. time of Day", option_D: "D. environment", rightAnswer: 1))
         list.append(Question(imgae: "", question: "      On a two-lane street your vehicle is being followed by a fire engine that is not using emergency signals. You should:", option_A: "A. continue to drive in a normal manner", option_B: "B. stop as quickly as you can", option_C: "C. speed up to get out of the way", option_D: "D. slow down; move as far to the right as possible and stop", rightAnswer: 1))
         list.append(Question(imgae: "", question: "     Which of these statements is true regarding making a left turn from a one-way street onto another one-way street?", option_A: "A.      signal well ahead of the turn and, when safe, move into the far-left lane of the streetslow down and begin your left turn after checking for traffic. ", option_B: "B. Shoulder check ", option_C: "C. unless otherwise indicated, you may turn left from a one-way street to a one-way street on a red light, after stopping and yielding the right-of-way to pedestrians and other traffic", option_D: "D.     all of the above", rightAnswer: 4))
         list.append(Question(imgae: "", question: " When operating your vehicle, headlights must be switched on: ", option_A: "A. when visibility is reduced to 60 metres ", option_B: "B. one hour before sunset to one hour after sunrise", option_C: "C. ½ hour before sunset to ½ hour after sunrise", option_D: "D. both a and c", rightAnswer: 4))
         list.append(Question(imgae: "", question: "      A vehicle's tires are required to be replaced when the tread depth is less than:", option_A: "A. 1.2 mm", option_B: "B. 1.6 mm", option_C: "C. 2.4 mm", option_D: "D. 1.8 mm ", rightAnswer: 2))
         list.append(Question(imgae: "", question: "     If you have driven through standing water deep enough to possibly get your brake shoes wet, you should:", option_A: "A.      press the brakes lightly to check for responsiveness", option_B: "B. drive slowly and apply brakes lightly to dry them", option_C: "C. just keep driving. The brakes will not be affected", option_D: "D. both a and b", rightAnswer: 4))
         list.append(Question(imgae: "", question: "Your vehicle should be checked for mechanical defects:", option_A: "A. only when a defect is noticeable", option_B: "B. just before you leave on a long trip", option_C: "C.once a year", option_D: "D. twice a year", rightAnswer: 4))
         list.append(Question(imgae: "", question: "      Persons driving under the influence of intoxicating liquor are:", option_A: "A. every driver's problem whether they drink or not", option_B: "B.  only a problem to their passengers", option_C: "C. not a problem in Manitoba", option_D: "D. a police enforcement problem only", rightAnswer: 1))
         list.append(Question(imgae: "", question: "     Failing to turn your head to check for traffic before changing lanes:", option_A: "A. is alright if you check the rear view mirror", option_B: "B. s a bad driving habit", option_C: "C. may contribute to a collision", option_D: "D. both b and c", rightAnswer: 4))
         list.append(Question(imgae: "", question: " Which of the following road markings allow passing on a highway?", option_A: "A. a double solid line", option_B: "B. a solid line", option_C: "C. a broken line", option_D: "D.a solid and broken line if the solid line is on your side of the highway", rightAnswer: 3))
         list.append(Question(imgae: "", question: " When an emergency vehicle (ambulance, fire or police), sounding an alarm and flashing its lights, is approaching from any direction, you must yield right of way by:", option_A: "A. immediately moving clear of an intersection if you are stopped for a red light or stop sign", option_B: "B. driving as closely as possible to the curb or edge of roadway and stopping", option_C: "C. remaining stopped at the edge of the road until the emergency vehicles have passed", option_D: "D. all of the above", rightAnswer: 4))
         list.append(Question(imgae: "", question: " A flashing red signal light means the same as a:", option_A: "A. yellow light", option_B: "B. stop sign", option_C: "C.yield sign", option_D: "D. caution sign", rightAnswer: 2))
         list.append(Question(imgae: "", question: "There is a 'reduce speed' sign ahead. As a driver you should know that:", option_A: "A. you should maintain your vehicle's speed till after you get to the slower speed zone", option_B: "B.you should begin to reduce your vehicle's speed", option_C: "C. it's dangerous to slow down because traffic starts to back up", option_D: "D. the sign is only meant for slower drivers", rightAnswer: 2))
         list.append(Question(imgae: "", question: " ", option_A: "A. ", option_B: "B. ", option_C: "C. ", option_D: "D. ", rightAnswer: 1))
        
        list.append(Question(imgae: "", question: " If your vehicle plunges into water, you should:", option_A: "A.get all the occupants out while the vehicle floats", option_B: "B. wait until the vehicle starts to sink", option_C: "C. wait in the vehicle for emergency assistance", option_D: "D. none of the above", rightAnswer: 1))
        list.append(Question(imgae: "", question: " If a vehicle suddenly approaches from the opposite direction in your lane", option_A: "A.brake hard and flash your headlights. If speed can be reduced before the collision, the impact will be less severe", option_B: "B.head for the shoulder on the right-hand side of the road and sound your horn", option_C: "C. drive into the ditch if necessary and head for something that is capable of energy absorption to reduce the force on impact", option_D: "D. all of the above", rightAnswer: 4))
        list.append(Question(imgae: "", question: " When passing a large vehicle, a driver of a small vehicle must be prepared for:", option_A: "A. a loud noise", option_B: "B. excess air pollution", option_C: "C.turbulent wind gusts produced by the large vehicle", option_D: "D. falling vehicle parts", rightAnswer: 3))
        list.append(Question(imgae: "", question: " The distance you follow behind another vehicle should be determined by:", option_A: "A. legal speed limit", option_B: "B. condition of vehicle", option_C: "C. speed and existing conditions", option_D: "D. type of highway", rightAnswer: 3))
        
        list.append(Question(imgae: "", question: "      When stopping at a railway crossing in a restricted speed area, always stop at least _____________ away from the nearest track.", option_A: "A.      2 metres", option_B: "B.      5 metres", option_C: "C.    10 metres", option_D: "D.      15 metres", rightAnswer: 2))
        list.append(Question(imgae: "", question: " When you are driving out of a back lane, driveway or parking lot, you must:", option_A: "A. stop only if there is a stop sign", option_B: "B. stop before crossing the sidewalk and yield to pedestrians and vehicles", option_C: "C. stop only if traffic is approaching", option_D: "D. drive out slowly so as not to hold up traffic behind you", rightAnswer: 2))
        list.append(Question(imgae: "", question: " On a two-way street, in what position must your vehicle be before making a left turn?", option_A: "A. to the right of and in the second lane from the center line", option_B: "B. any lane on your side of the roadway", option_C: "C.to the left of the center line so other traffic cannot pass", option_D: "D. to the right of and as close to the center line as practical", rightAnswer: 4))
        list.append(Question(imgae: "", question: " Alcohol's effect on your reflexes and judgement: ", option_A: "A. is less if you only drink beer", option_B: "B. is less if you only drink wine", option_C: "C.is greater if you drink whiskey or hard liquor", option_D: "D. depends on the amount of alcohol in your blood stream", rightAnswer: 4))
        
        list.append(Question(imgae: "", question: "An inattentive driver:", option_A: "A.      daydreams or gazes at objects off the roadway while driving", option_B: "B. arries on an eye-contact conversation with a passenger while driving", option_C: "C. restricts attention to only watching the vehicle ahead", option_D: "D. all of the above", rightAnswer: 4))
        list.append(Question(imgae: "", question: " Before changing lanes, check your mirrors for traffic, signal your intention to move and:", option_A: "A. accelerate to make the change", option_B: "B. check blind spots and adjust your speed as required", option_C: "C. decelerate and adjust your speed as required", option_D: "D.steer into the lane you wish to change to", rightAnswer: 2))
        list.append(Question(imgae: "", question: "     If your vehicle's turn signals don't work and you plan on making a right turn, what is the proper hand signal? ", option_A: "A. left arm positioned outside the window, straight out", option_B: "B. left arm positioned outside the left window, upward at a 90° angle", option_C: "C. left arm positioned downward outside, the window at a 90° angle", option_D: "D.right arm positioned out to the right", rightAnswer: 2))
        list.append(Question(imgae: "", question: "You intend to parallel park. Before backing into the spot, you should: ", option_A: "A. check the mirror and blind spot", option_B: "B. check oncoming traffic, to the rear, your blind spots, both sides and then turn to the right and look to the rear", option_C: "C. check blind spots", option_D: "D. assume the backing to the right position and look out the rear window", rightAnswer: 2))
        
        
        list.append(Question(imgae: "", question: "     Broken yellow lines on a roadway mean:", option_A: "A.      traffic is moving in the same direction ", option_B: "B. traffic is moving in the opposite direction", option_C: "C. you are in a parking lane", option_D: "D. no passing is allowed", rightAnswer: 2))
        list.append(Question(imgae: "", question: "     U-turns are prohibited at which of the following locations:", option_A: "A.      on curves", option_B: "B.      approaches to or near the crest of a hill where there is not at least a 150-metre clear view of oncoming traffic ", option_C: "C.      middle of a block", option_D: "D. all of the above", rightAnswer: 4))
        list.append(Question(imgae: "", question: "On big trucks, there are large blind spots called No-Zones around the truck. Which of the following No-Zones should you avoid?", option_A: "A. the area in front of the truck", option_B: "B. the area directly behind the truck", option_C: "C. the sides of the truck", option_D: "D. all of the above", rightAnswer: 4))
        list.append(Question(imgae: "", question: "     While driving you come upon a sign which reads, 'Maximum speed 60 km/h ahead'. You as a driver should know:", option_A: "A. that the new 60-km/h-speed zone begins at this sign", option_B: "B. that the new 60-km/h-speed zone begins at the 'Maximum speed' sign", option_C: "C. that you have plenty of time to slow down before the speed zone", option_D: "D. that the sign is only intended for the local residents", rightAnswer: 2))
       // list.append(Question(imgae: "", question: "You are driving and a front tire blows out. You should:", option_A: "A. ", option_B: "B. ", option_C: "C. ", option_D: "D. ", rightAnswer: 2))
        list.append(Question(imgae: "", question: "You are driving and a front tire blows out. You should:", option_A: "A. brake quickly and firmly", option_B: "B. hold your steering wheel firmly, take your foot off the accelerator, reduce your speed, brake gradually and steer to the shoulder", option_C: "C. pump the brake", option_D: "D. turn on your emergency flashers", rightAnswer: 2))
        list.append(Question(imgae: "", question: "     What is considered a safe speed?", option_A: "A. speed that allows you to stop for an emergency", option_B: "B. going five kms below the speed limit", option_C: "C. driving with the flow of traffic", option_D: "D. doing the speed limit", rightAnswer: 1))
        list.append(Question(imgae: "", question: "     In what lane of traffic should you drive when you are going to make a right turn?", option_A: "A. in the second lane from the right side of the roadway", option_B: "B. close to the right side of the roadway", option_C: "C. any lane on your side of the roadway", option_D: "D. close to the center line of the roadway", rightAnswer: 2))
        list.append(Question(imgae: "RoadSign_2-0", question: "     This sign means:", option_A: "A. curve in the road", option_B: "B. right curve ahead", option_C: "C. right turn ahead", option_D: "D. all traffic move right", rightAnswer: 2))
        list.append(Question(imgae: "RoadSign_7-0", question: "     This sign means:", option_A: "A. traffic must turn right", option_B: "B. very sharp right turn ", option_C: "C. traffic move right", option_D: "D. curve in the road", rightAnswer: 2))
        list.append(Question(imgae: "RoadSign_28-0", question: "     This sign means:", option_A: "A. low overhead clearance", option_B: "B. hidden intersection ahead", option_C: "C. yield ahead", option_D: "D. hazard marker showing an obstruction ", rightAnswer: 4))
        list.append(Question(imgae: "RoadSign_30-0", question: "     This sign means:", option_A: "A.      pedestrian crosswalk ahead", option_B: "B. children at play", option_C: "C. playground area ahead", option_D: "D. school crosswalk ahead", rightAnswer: 4))
        list.append(Question(imgae: "RoadSign_34-0", question: "     This sign means:", option_A: "A. right turn only", option_B: "B. reserved lane located in curb lane", option_C: "C. no right turns between 08:00 - 17:30", option_D: "D. truck lane only", rightAnswer: 2))
        list.append(Question(imgae: "RoadSign_52-0", question: "     This sign means:", option_A: "A. enter at your own risk", option_B: "B. road ends", option_C: "C. road closed", option_D: "D. do not enter ", rightAnswer: 4))
        list.append(Question(imgae: "RoadSign_14-0", question: "     This sign means:", option_A: "A. median ahead", option_B: "B. entering a town, city or village", option_C: "C. divided highway begins ahead", option_D: "D. road ends ahead", rightAnswer: 3))
        list.append(Question(imgae: "RoadSign_42-0", question: "     This sign means:", option_A: "A. rough road", option_B: "B. slippery when wet", option_C: "C. ice covered", option_D: "D. bump ahead", rightAnswer: 4))
        list.append(Question(imgae: "RoadSign_47-0", question: "     This sign means:", option_A: "A. road work", option_B: "B.      playground area", option_C: "C. public gardens ahead", option_D: "D.      tree plantation ahead", rightAnswer: 1))
        list.append(Question(imgae: "RoadSign_53-0", question: "     This sign means:", option_A: "A. all traffic must slow down", option_B: "B. exit lane", option_C: "C. all traffic must turn left  ", option_D: "D.      buses may turn left", rightAnswer: 3))
        list.append(Question(imgae: "RoadSign_68-0", question: "     This sign means:", option_A: "A. one-way traffic", option_B: "B. no passing allowed", option_C: "C. two-way traffic ", option_D: "D. passing allowed", rightAnswer: 3))
        list.append(Question(imgae: "RoadSign_70-0", question: "     This sign means:", option_A: "A. two lane traffic", option_B: "B. passing permitted ", option_C: "C. three lane street ahead", option_D: "D. right lane ends", rightAnswer: 2))
        list.append(Question(imgae: "RoadSign_75-0", question: "     This sign means:", option_A: "A.      playground corridor", option_B: "B. pedestrian corridor", option_C: "C. school ground corridor", option_D: "D. school crossing", rightAnswer: 2))
        
      //  list.append(Question(imgae: "", question: "", option_A: "A. ", option_B: "B. ", option_C: "C. ", option_D: "D. ", rightAnswer: 2))
        
        
        
        
        
    }
}
